version: 2

############################################################################

references:
   build_job_steps: &build_job_steps
      steps:
         - checkout
         - run:
            name: Creating build
            command: |
               ./build.pl \
                  --build-type=FOSS \
                  --build-hostname=build.zimbra.org \
                  --build-release="$CIRCLE_PROJECT_USERNAME" \
                  --build-release-no=$(.circleci/misc/glean_version.pl) \
                  --build-release-candidate=beta \
                  --build-thirdparty-server=zdev-vm008.eng.zimbra.com \
                  --deploy-url-prefix="https://files.zimbra.com/dev-releases" \
                  --git-default-branch="$CIRCLE_BRANCH,develop" \
                  --build-os="$ZIMBRA_BUILD_OS" \
                  --build-no="$CIRCLE_BUILD_NUM" \
                  --build-ts="$(date "+%Y%m%d%M%H%S")" \
                  --ant-options="-DskipTests=1" \
                  --no-interactive \
                  --disable-bundle \
                  2>&1 | tee -a build.log;
               mkdir -p ../BUILDS
               mv build.log ../BUILDS/build-${ZIMBRA_OS_TAG}.log
         - store_artifacts:
            path: ../BUILDS
         - persist_to_workspace:
            root: ../BUILDS
            paths: ./*

   stub_build_job_steps: &stub_build_job_steps
      steps:
         - run:
            name: Creating nothing
            command: |
               date
               echo nothing

   deploy_s3_job_steps: &deploy_s3_job_steps
      steps:
         - checkout
         - attach_workspace:
            at: ../BUILDS
         - deploy:
            command: .circleci/jobs/deploy_s3/deploy.sh

   deploy_ec2_job_steps: &deploy_ec2_job_steps
      steps:
         - checkout
         - attach_workspace:
            at: ../BUILDS
         - deploy:
            command: .circleci/jobs/deploy_ec2/deploy.sh ${OPERATION}

   std_filters: &std_filters
      filters:
         branches:
            only:
               - master
               - develop

############################################################################

jobs:
   build_u16:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: u16
         - ZIMBRA_BUILD_OS: UBUNTU16_64
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-16.04
      <<: *build_job_steps

   build_u14:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: u14
         - ZIMBRA_BUILD_OS: UBUNTU14_64
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-14.04
      <<: *build_job_steps

   build_u12:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: u12
         - ZIMBRA_BUILD_OS: UBUNTU12_64
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-12.04
      <<: *build_job_steps

   build_r7:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: r7
         - ZIMBRA_BUILD_OS: RHEL7_64
      docker:
         - image: zimbra/zm-base-os:devcore-centos-7
      <<: *build_job_steps

   build_r6:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: r6
         - ZIMBRA_BUILD_OS: RHEL6_64
      docker:
         - image: zimbra/zm-base-os:devcore-centos-6
      <<: *build_job_steps

   deploy_s3:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:core-ubuntu
      <<: *deploy_s3_job_steps

   deploy_ec2@app1_install:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - OPERATION: install
      docker:
         - image: zimbra/zm-base-os:core-ubuntu
      <<: *deploy_ec2_job_steps

   deploy_ec2@app1_upgrade:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - OPERATION: upgrade
      docker:
         - image: zimbra/zm-base-os:core-ubuntu
      <<: *deploy_ec2_job_steps

############################################################################

workflows:
   version: 2
   build_and_deploy:
      jobs:
         - build_u16
         - build_u14
         - build_u12
#         - build_r7    (core dump issue while running ant)
         - build_r6

         - deploy_s3_hold:
            type: approval
            requires:
               - build_u16
               - build_u14
               - build_u12
#               - build_r7    (core dump issue while running ant)
               - build_r6
            <<: *std_filters

         - deploy_s3:
            requires:
               - deploy_s3_hold
            <<: *std_filters

         - app1_ec2_install:
            type: approval
            requires:
               - build_u16
            <<: *std_filters

         - app1_ec2_upgrade:
            type: approval
            requires:
               - build_u16
            <<: *std_filters

         - deploy_ec2@app1_install:
            requires:
               - app1_ec2_install
            <<: *std_filters

         - deploy_ec2@app1_upgrade:
            requires:
               - app1_ec2_upgrade
            <<: *std_filters
